site_name: Oferta Académica UTPL
site_description: Catálogo oficial de facultades y carreras de la UTPL.
site_author: Universidad Técnica Particular de Loja

theme:
  name: material  # Esto le da el look profesional
  palette:
    primary: indigo
    accent: blue
  features:
    - navigation.tabs  # Menú horizontal superior

nav:
  - Inicio: index.md
  - Ciencias Exactas e Ingenierías: ingenierias.md
  - Ciencias Sociales y Humanidades: sociales.md
  - Ciencias Económicas y Empresariales: administrativas.md
  - Ciencias de la Salud: salud.md

markdown_extensions:
  - tables  # Necesario para que las tablas de carreras se vean bien
